sudo: required
dist: focal
language: cpp

cache:
  ccache: true

matrix:
  include:
    # gcc
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
        - COVERALLS_SERVICE_NAME=travis-ci
        - secure: H8JjZT7juIz0CNHmV01gPLhTWPBjVV9RNCvSQtxtGxCn4y0GwsSFB7T3nFLw2cSYYjBNkcYsierIrPau68fV2B03cdr+9GnRM+eFFHbiLIzzvZoysfHTZvl2ElCLc96fS6bko++vPc7FQEdNAphvSKZSN05UbR5sFKtgeykViEEAdmFYPG+ZMex7Exq+2YUANjQxBVGhPQ4/t3FNhKc+ByvQzxlO8MfmxNVLUwJsW9W/wb0ruXl1CFc15bXBts/DBAn+voJpqvl7+1GtlvcahMiSbKBi0aiqihlAcohw6c6x7IYXFekO0cNcAhFNeF2VM6b2DBY8wFQ07K2o0tXKovBdSdxTSmmfAKlKyYXYdtI47vtF0mIcx08nkuPNEbzeWyPOgMxKd6Ffa9XMf2e9zN6+2XwjvoIb3SjPl0mz41pp0MRSSxkTQdifUfXQthMFYPPTq734O4J/aIpB4AygkqeGnZtg140erqSeUG2prVB4EekCZwPAqk/4LCA2VIGf+PtqrCZDFk0dRW1SXViz67/7GqyIu4dkOMitEOLtqjO09roQHK9TP/QuWtlGWtJ+oaANNK7D+ciCM3gP5FmH6Se/OrqyUgJN+LLI/wJscDSPgiXPXNs44d85tLdsbG+hzrvj0IaMR0anqT5pDqaHYlKRhfFHZbbJyQ+yeItWhk8=
      branches:
      except:
        - gh-pages
        - documentation

    # clang
    - os: linux
      addons:
        apt:
          packages:
            - clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
      branches:
      except:
        - gh-pages
        - documentation

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl language-pack-de
  - pwd
  - ls
  - pip install --user --upgrade cmake
  - pip install --user cpp-coveralls

script:
  - mkdir build && cd build
  - cmake --version
  - cmake -DUNITS_BUILD_TESTS=ON -DUNITS_CODE_COVERAGE=ON ..
  - cmake --build . --config Release -- -Werror
  - cmake --build . --config Debug -- -Werror

test:
  - cd test
  - ctest -C Release -V

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'