sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update -qq
  
install:
  - sudo apt-get install cmake-3.4.1 -y
  - sudo apt-get install g++-4.9 -y
  - export CXX="g++-4.9"
  
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
