os: Visual Studio 2015

clone_folder: c:/projects/units

branches:
  except:
    - gh-pages
    - documentation

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  matrix:
    - VS_GEN: Visual Studio 12 2013 Win64
    - VS_GEN: Visual Studio 14 2015 Win64
	
build_script:
  - md build
  - cd build
  - cmake -Wno-dev -G"%VS_GEN%" ..
  - cmake --build . --config %CONFIGURATION%

test_script:
  - cmd: ctest -VV -C %CONFIGURATION%
