os: Visual Studio 2015

clone_folder: c:/projects/units

platform:
  - x64
  
configuration:
  - Debug
  - Release
 
before_build:
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="x64" cmake -G"Visual Studio 14 Win64" ..

build:
  project: C:/projects/units/build/units.sln

test_script:
  - cmd: ctest -VV -C %CONFIGURATION%
